// src/components/ImageC.tsx
import Link from "next/link";
const ImageC: React.FC<{
  image: string;
  caption: string;
  notfound?: "gone" | "img";
}> = (props) => {
  const condition = props.notfound ?? "img";

  return (
    <>
      <div
        className="image-c"
        // style={gone ? { display: "none" } : {}}
      >
        <img
          src={props.image}
          alt="Image With Caption"
          // onError={(e) => {
          //   if (props.notfound === "gone") {              return;
          //   }
          //   e.currentTarget.onerror = null;
          //   e.currentTarget.src = "/notfound.webp";
          // }}
        />
        <p>{props.caption}</p>
      </div>
    </>
  );
};

export default ImageC;

// src/lib/ImageC.svelte
<script lang="ts">
  export let image: string;
  export let caption: string;
  export let notfound: "gone" | "img" = "img";

  let gone = false;
</script>

{#if gone}
  <div class="image-c" />
{:else}
  <div class="image-c">
    <img
      src={image}
      alt={caption}
      on:error={(e) => {
        if (notfound === "gone") {
          gone = true;
          return;
        }
        //@ts-ignore
        e.currentTarget.onerror = null;
        //@ts-ignore
        e.src = "/notfound.webp";
      }}
    />
    <p>{caption}</p>
  </div>
{/if}
