// src/components/Letter.tsx
import ReactMarkdown from "react-markdown";
import ImageC from "./ImageC";

const Letter: React.FC<{
  sender: string;
  content: string;
  signatures: {
    members: {
      signature: string;
      name: string;
      role: string;
    };
  }[];
}> = (props) => {
  return (
    <div className="letter">
      <h1>Letter From {props.sender}</h1>

      <ReactMarkdown
        components={{
          // @ts-ignore
          p: (paragraph: { children?: boolean; node?: any }) => {
            const { node } = paragraph;

            if (node.children[0].tagName === "image") {
              const image = node.children[0];
              const caption = image.properties.alt;

              return <ImageC image={image.properties.src} caption={caption} />;
            }
            return <p>{paragraph.children}</p>;
          },
        }}
      >
        {props.content}
      </ReactMarkdown>
      <div className="letter__signatures">
        {props.signatures.length > 0 &&
          props.signatures.map((e) => {
            return (
              <div key={e.members.name} className="letter__signatures--item">
                <div className="letter__signatures--wrap">
                  <img
                    src={`https://apis.news.newton.ac.th/images${e.members.signature}`}
                  />
                </div>
                <span>
                  <h3>{e.members.name}</h3>
                  <h4>{e.members.role}</h4>
                </span>
              </div>
            );
          })}
      </div>
    </div>
  );
};

export default Letter;

// src/lib/Letter.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import SvelteMarkdown from "svelte-markdown";

  export let sender: string;
  export let content: string;
  export let signatures: {
    members: {
      signature: string;
      name: string;
      role: string;
    };
  }[];
  onMount(() => {
    signatures.sort((a: any, b: any) => {
      return a.members.role.startsWith("Founder") ? -10 : 1;
    });
  });
</script>

<div class="letter">
  <h1>Letter From <em>{sender}</em></h1>
  <p>
    <SvelteMarkdown source={content} />
  </p>

  <div class="letter__signatures">
    {#each signatures as e}
      <!-- content here -->
      <div class="letter__signatures--item">
        <div class="letter__signatures--wrap">
          <img
            src={`https://apis.news.newton.ac.th/images${e.members.signature}`}
            alt="{e.members.name}'s signature"
          />
        </div>
        <span>
          <h3>{e.members.name}</h3>
          <h4>{e.members.role}</h4>
        </span>
      </div>
    {/each}
  </div>
</div>
