// src/routes/members/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
</script>

<div class="members">
  <section class="members__important">
    {#each data.important as cur}
      <a href={`/members/${cur.id}`}>
        <div class="members__important--card">
          <img src={cur.profile} alt={`portrait of ${cur.name}`} />
          <h4>{cur.role}</h4>
          <h3>
            {cur.name}<br />({cur.nickname})
          </h3>
          <h5>
            Year {cur.year}
            {cur.track}
          </h5>
        </div>
      </a>
    {/each}
  </section>
  <section class="members__list">
    {#each data.members as cur}
      <a href={`/members/${cur.id}`}>
        <div class="members__list--card">
          <img src={cur.profile} alt={`portrait of ${cur.name}`} />
          <h4>{cur.role}</h4>
          <h3>
            {cur.name}<br />({cur.nickname})
          </h3>
          <h5>
            Year {cur.year}
            {cur.track}
          </h5>
        </div>
      </a>
    {/each}
  </section>
</div>

// apps/the-newtonian/src/pages/Members.tsx
import { useState } from "react";

const Members = () => {
  const [important, setImportant] = useState([
    {
      name: "Yanitta Iewwongcharoen (Krapook)",
      image: "/members/image.jpeg",
      year: "13",
      track: "Humanity",
      position: ["Editor-in-chief"],
    },
    {
      name: "Yanitta Iewwongcharoen (Krapook)",
      image: "/members/image.jpeg",
      year: "13",
      track: "Humanity",
      position: ["Editor-in-chief"],
    },
  ]);

  return (
    <div className="members__wrapper">
      <div className="members">
        <section className="members__important">
          {important &&
            important.map((cur) => (
              <div className="members__important--card">
                <img
                  src={cur.image}
                  alt=""
                  className="members__important--image"
                />
                <h3>{cur.name}</h3>
              </div>
            ))}
        </section>
      </div>
    </div>
  );
};

export default Members;
