// src/lib/IssueCard.svelte
<script lang="ts">
  import nth from "./utils/nth";

  export let publishingDate: string;
  export let no: number;
  export let cover: string;
</script>

<div class="issue-card">
  <a href={`/issues/${no}`}>
    <div class="issue-card__cover">
      <img src={`https://apis.news.newton.ac.th/images${cover}`} alt="issue {no}'s cover" />
    </div>
    <div class="issue-card__info">
      <h3>Issue {no}</h3>
      <h4>{nth(publishingDate)}</h4>
    </div>
  </a>
</div>

// apps/the-newtonian/src/components/IssueCard.tsx
import { Link } from "react-router-dom";
import ImageC from "./ImageC";

const IssueCard: React.FC<{ date: string; no: number; cover: string }> = (
  props
) => {
  return (
    <div className="issue-card">
      <Link to={`/issues/${props.no}`}>
        <div className="issue-card__cover">
          <img src={props.cover} />
        </div>
        <div className="issue-card__info">
          <h3>Issue {props.no}</h3>
          <h4>
            {new Date(props.date).toLocaleDateString("en-UK", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })}
          </h4>
        </div>
      </Link>
    </div>
  );
};

export default IssueCard;
