// src/lib/layout/Header.svelte
<div class="header__wrapper">
  <div class="header">
    <div class="header__logo">
      <a href="/">
        <img src="/logo.svg" alt="The Newtonian Logo" class="header__logo--light" />
        <img src="/logo-dark.svg" alt="The Newtonian Logo" class="header__logo--dark" />
      </a>
    </div>
    <div class="header__nav">
      <ul>
        <li>
          <a href={"/articles"}>Articles</a>
        </li>
        <li>
          <a href={"/issues"}>Issues</a>
        </li>
        <li>
          <a href={"/members"}>Members</a>
        </li>
        {#if true}
          <li>
            <a style="color: #CC3333;" href={"/eics"}> Eics </a>
          </li>
        {/if}
      </ul>
    </div>
  </div>
</div>

// apps/the-newtonian/src/components/layout/Header.tsx
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <div className="header__wrapper">
      <div className="header">
        <div className="header__logo">
          <Link to="/">
            <img src="/logo.png" />
          </Link>
        </div>
        <div className="header__nav">
          <ul>
            <li key={"ca"}>
              <Link to={"/categories"}>Categories</Link>
            </li>
            <li key={"iss"}>
              <Link to={"/issues"}>Issues</Link>
            </li>
            <li key={"members"}>
              <Link to={"/members"}>Members</Link>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default Header;
