// src/routes/members/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";

  interface member {
    id: number;
    name: string;
    nickname: string;
    profile: string;
    year: string;
    status: string;
    track: string;
    role: string;
    permission: number;
  }

  export let data: PageData;

  let important: member[] = [];
  let members: member[] = [];

  const sorter = async () => {
    important = data.members.filter((cur) => {
      return cur.permission === 5;
    });
    members = data.members.filter((cur) => {
      return cur.permission < 5;
    });

    console.log({ important });
  };

  let sorting = sorter();
</script>

<title>Members | The Newtonian</title>

{#await sorting then}
  <div class="members__wrapper">
    <div class="members">
      <section class="members__important">
        {#each important as cur}
          <a href={`/members/${cur.id}`}>
            <div class="members__important--card">
              <img
                src={`https://apis.news.newton.ac.th/images${cur.profile}`}
                alt=""
                class="members__important--image"
                on:error={(e) => {
                  //@ts-ignore
                  e.currentTarget.onerror = null;
                  //@ts-ignore
                  e.currentTarget.src = "/notfound.webp";
                }}
              />
              <h3>
                {cur.name}
                <br />({cur.nickname})
              </h3>
              {#if cur.track !== "supervisor"}
                <h4>
                  Year {cur.year} - {cur.track}
                </h4>
              {/if}
              <h4>{cur.role}</h4>
            </div>
          </a>
        {/each}
      </section>
      <section class="members__list">
        {#each members as cur}
          <a href={`/members/${cur.id}`}>
            <div class="members__list--card">
              <img
                src={`https://apis.news.newton.ac.th/images${cur.profile}`}
                alt=""
                class="members__list--image"
                on:error={(e) => {
                  //@ts-ignore
                  e.currentTarget.onerror = null;
                  //@ts-ignore
                  e.currentTarget.src = "/notfound.webp";
                }}
              />
              <h3>
                {cur.name}
                <br />({cur.nickname})
              </h3>
              {#if cur.track !== "supervisor" && cur.status === "ACTI"}
                <h4>
                  Year {cur.year} - {cur.track ? cur.track : ""}
                </h4>
              {:else if cur.status !== "ACTI"}
                {#if cur.status === "LEAV"}
                  <h4 style="font-style: italic;">Leaved</h4>
                {/if}
                {#if cur.status === "GRAD"}
                  <h4 style="font-style: italic;">Graduated</h4>
                {/if}
                {#if cur.status === "LEAV"}
                  <h4 style="font-style: italic;">Contestant (Award Winner)</h4>
                {/if}
              {:else}
                <h4>Supervisor</h4>
              {/if}
              <h4>{cur.role}</h4>
            </div>
          </a>
        {/each}
      </section>
    </div>
  </div>
{/await}

// src/pages/Members.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Loading from "../components/Loading";

const Members = () => {
  const [important, setImportant] = useState([
    {
      id: "",
      name: "Yanitta Iewwongcharoen (Krapook)",
      nickname: "Yanitta Iewwongcharoen (Krapook)",
      profile: "/members/krapook.png",
      year: "13",
      status: "",

      track: "Humanities",
      role: "Editor-in-chief",
    },
  ]);
  const [members, setMembers] = useState([
    {
      id: "",
      name: "Yanitta Iewwongcharoen (Krapook)",
      nickname: "Yanitta Iewwongcharoen (Krapook)",
      profile: "/members/krapook.png",
      year: "13",
      track: "Humanities",
      status: "",
      role: "Editor-in-chief",
    },
  ]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    document.title = `Members | The Newtonian`;

    fetch(`https://apis.news.newton.ac.th/api/member`)
      .then((data) => {
        console.log(data);
        return data.json();
      })
      .then((data) => {
        console.log(data);
        const importantList: any[] = [];
        const memberList: any[] = [];
        data.map((e: any) => {
          console.log(e);
          let isImportant = false;

          if (e.role.endsWith("Editor-in-chief")) isImportant = true;

          if (isImportant) return importantList.push(e);
          return memberList.push(e);
        });

        let important = data.filter((cur: any) => {
          return cur.permission === 5;
        });
        let members = data.filter((cur: any) => {
          return cur.permission < 5;
        });

        setImportant(important);
        setMembers(members);
        setIsLoading(false);
      });
  }, []);

  if (isLoading) return <Loading />;

  return (
    <div className="members__wrapper">
      <div className="members">
        <section className="members__important">
          {important &&
            important.map((cur) => (
              <Link to={`/member/${cur.id}`}>
                <div className="members__important--card">
                  <img
                    src={`https://apis.news.newton.ac.th/images${cur.profile}`}
                    alt=""
                    className="members__important--image"
                    onError={(e) => {
                      e.currentTarget.onerror = null;
                      e.currentTarget.src = "/notfound.webp";
                    }}
                  />
                  <h3>
                    {cur.name}
                    <br />({cur.nickname})
                  </h3>
                  <h4>
                    Year {cur.year} - {cur.track}
                  </h4>
                  <h4>{cur.role}</h4>
                </div>
              </Link>
            ))}
        </section>
        <section className="members__list">
          {members &&
            members.map((cur) => (
              <Link to={`/member/${cur.id}`}>
                <div className="members__list--card">
                  <img
                    src={`https://apis.news.newton.ac.th/images${cur.profile}`}
                    alt=""
                    style={
                      cur.status !== "ACTI" ? { filter: "grayscale(1)" } : {}
                    }
                    className="members__list--image"
                    onError={(e) => {
                      e.currentTarget.onerror = null;
                      e.currentTarget.src = "/notfound.webp";
                    }}
                  />
                  <h3>
                    {cur.name}
                    <br />({cur.nickname})
                  </h3>
                  <h4>
                    Year {cur.year} {cur.track ? " - " + cur.track : ""}
                  </h4>
                  <h4>{cur.role}</h4>
                  {cur.status === "LEAV" && (
                    <h4 style={{ fontStyle: "italic" }}>Leaved</h4>
                  )}
                  {cur.status === "GRAD" && (
                    <h4 style={{ fontStyle: "italic" }}>Graduated</h4>
                  )}{" "}
                  {cur.status === "CONS" && (
                    <h4 style={{ fontStyle: "italic" }}>
                      Contestant (Award Winner)
                    </h4>
                  )}
                </div>
              </Link>
            ))}
        </section>
      </div>
    </div>
  );
};

export default Members;
