// src/components/layout/Footer.tsx
const Footer = () => {
  return (
    <div className="footer__wrapper">
      <div className="footer">
        <div className="footer__copy">
          All Rights Reserved &copy; 2022 The Newtonian
        </div>

        <div className="footer__right">
          <h4>The Newtonian Online Version 1.3</h4>
        </div>
      </div>
    </div>
  );
};

export default Footer;

// src/lib/layout/Footer.svelte
<div class="footer__wrapper">
  <div class="footer">
    <div class="footer__copy">
      All Rights Reserved &copy; 2022-23 The Newtonian Newspaper - <a href="https://newton.ac.th"
        >The Newton Sixth Form School</a
      >
    </div>

    <div class="footer__right">
      <h4>
        The Newtonian Online Version 2.0 <br /><em
          >Written by <a href="/members/1">Prawich Thawansakdivudhi</a></em
        >
      </h4>
    </div>
  </div>
</div>
