// src/routes/articles/+page.svelte
<script lang="ts">
  import ArticleList from "$lib/ArticleList.svelte";
  import type { PageData } from "./$types";

  export let data: PageData;

  const catergories = [
    { name: "Letter", id: "Letter" },
    {
      name: "Interview",
      id: "Interview",
    },
    {
      name: "School Update",
      id: "SchoolUpdate",
    },
    {
      name: "Advice / Essay",
      id: "AdviceEssay",
    },
    {
      name: "Fiction / Poetry",
      id: "Fiction",
    },
    {
      name: "Research",
      id: "Research",
    },
    {
      name: "Performing Arts",
      id: "PerformingArts",
    },
    {
      name: "Visual Arts",
      id: "VisualArts",
    },
    {
      name: "Review",
      id: "Review",
    },
    {
      name: "Business by NBS",
      id: "NBS",
    },
  ];

  const categorised: any = {};

  catergories.forEach((c) => {
    categorised[c.id] = data.data.filter((a: any) => a.category === c.id);
  });

  console.log(catergories);
</script>

<title>Articles | The Newtonian</title>
<div class="categories__wrapper">
  <div class="categories">
    {#each catergories as c, i}
      <section class="categories__articles">
        <ArticleList title={c.name} articles={categorised[c.id].reverse()} />
      </section>
    {/each}
  </div>
</div>

// src/app/articles/page.tsx
import ArticleList from "@/components/ArticleList";
import { articleData } from "./[id]/page";
import Head from "next/head";

const catergories = [
  { name: "Letter", id: "Letter" },
  {
    name: "Interview",
    id: "Interview",
  },
  {
    name: "School Update",
    id: "SchoolUpdate",
  },
  {
    name: "Advice / Essay",
    id: "AdviceEssay",
  },
  {
    name: "Fiction / Poetry",
    id: "Fiction",
  },
  {
    name: "Research",
    id: "Research",
  },
  {
    name: "Performing Arts",
    id: "PerformingArts",
  },
  {
    name: "Visual Arts",
    id: "VisualArts",
  },
  {
    name: "Review",
    id: "Review",
  },
  {
    name: "Business by NBS",
    id: "NBS",
  },
];

async function fetchArticles() {
  const data = await fetch(
    `https://apis.news.newton.ac.th/api/reader/article`,
    { next: { revalidate: 60 } }
  );

  return data.json() as Promise<articleData[]>;
}

export default async function Articles() {
  const articles = await fetchArticles();

  return (
    <div className="categories__wrapper">
      <Head>
        <title>Articles | The Newtonian</title>
      </Head>
      <div className="categories">
        {catergories &&
          catergories.map((c) => {
            const l = articles.filter((a) => a.category === c.id);

            return (
              <section className="categories__articles">
                <ArticleList
                  headline={c.name}
                  articles={l.reverse()}
                  error="We do not have any published article(s) related to this topic yet."
                />
              </section>
            );
          })}
      </div>
    </div>
  );
}
