// src/app/members/[id]/page.tsx
import ImageC from "@/components/ImageC";
import { Member } from "../page";
import ArticleList from "@/components/ArticleList";

const fetchMemberData = async (id: number) => {
  const data = await fetch(`https://apis.news.newton.ac.th/api/member/${id}`);

  return data.json() as Promise<Member>;
};

const Member = async ({ params }: { params: { id: string } }) => {
  const memberData = await fetchMemberData(+params.id);
  let memberStatus: string;

  switch (memberData.status) {
    case "ACTI":
      memberStatus = "Active";
      break;
    case "GRAD":
      memberStatus = "Graduated";
      break;
    case "CONS":
      memberStatus = "Award Winner";
      break;
    case "LEAV":
      memberStatus = "Resigned";
      break;
    default:
      memberStatus = "Active";
      break;
  }
  // console.log({ memberData });

  return (
    <div className="member__wrapper">
      <div className="member">
        <div className="member__info">
          <div className="member__info--left">
            <div className="member__info--image">
              <ImageC
                image={`https://apis.news.newton.ac.th/images${memberData.profile}`}
                caption={`${memberData.nickname}'s image`}
                notfound="img"
                height={280}
              />
            </div>
            <div className="member__info--bio">
              <h3>
                {memberData.name} ({memberData.nickname})
              </h3>
              <h4>
                Year {memberData.year} - {memberData.track}{" "}
                <span style={{ fontStyle: "italic" }}>({memberStatus})</span>
              </h4>
              <h5 style={{ color: "var(--signature-grey)" }}>
                {memberData.role}
              </h5>
              <p>{memberData.bio}</p>
            </div>
          </div>
          <div className="member__info--right">
            <img
              src={`https://apis.news.newton.ac.th/images${memberData.signature}`}
              alt="Member's Signature"
            />
          </div>
        </div>
        <ArticleList
          headline={"Articles"}
          articles={memberData.articles}
          error="This member has not published any article"
        />
      </div>
    </div>
  );
};

export default Member;

// src/routes/members/[id]/+page.svelte
<script lang="ts">
  import ArticleList from "$lib/ArticleList.svelte";
  import ImageC from "$lib/ImageC.svelte";
  import type { PageData } from "./$types";

  export let data: PageData;
</script>

<title>{data.name} | The Newtonian</title>

<div class="member__wrapper">
  <div class="member">
    <div class="member__info">
      <div class="member__info--left">
        <div class="member__info--image">
          <ImageC
            image={`https://apis.news.newton.ac.th/images${data.profile}`}
            caption={`${data.nickname}'s image`}
          />
        </div>
        <div class="member__info--bio">
          <h3>
            {data.name} ({data.nickname})
          </h3>
          {#if data.track !== "supervisor" && data.status === "ACTI"}
            <h4>
              Year {data.year} - {data.track ? data.track : ""}
            </h4>
          {:else if data.status !== "ACTI"}
            {#if data.status === "LEAV"}
              <h4 style="font-style: italic;">Leaved</h4>
            {/if}
            {#if data.status === "GRAD"}
              <h4 style="font-style: italic;">Graduated</h4>
            {/if}
            {#if data.status === "LEAV"}
              <h4 style="font-style: italic;">Contestant (Award Winner)</h4>
            {/if}
          {:else}
            <h4>Supervisor</h4>
          {/if}
          <h5 style="color: var(--signature-grey);">
            {data.role}
          </h5>
          <p>{data.bio}</p>
        </div>
      </div>
      <div class="member__info--right">
        <img
          src={`https://apis.news.newton.ac.th/images${data.signature}`}
          alt="Member's Signature"
        />
      </div>
    </div>
    <ArticleList
      title={"Articles"}
      articles={data.articles}
      error="This member has not yet published any article(s)"
    />
  </div>
</div>
